{{- $root := . -}} # To load values from file outside of range loop

{{- if .Values.arr_elements }}
  {{- range $k, $v := .Values.arr_elements }}
  {{- if $v.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: usenet
    run: {{ $k }}
  name: {{ $k }}
  namespace: {{ $root.Values.common.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usenet
      run: {{ $k }}
  template:
    metadata:
      labels:
        app: usenet
        run: {{ $k }}
    spec:
      hostname: {{ $k }}
      containers:
      - env:
        - name: TZ
          value: {{ $root.Values.common.timezone }}
        - name: PUID
          value: {{ $root.Values.common.PUID | quote }}
        - name: PGID
          value: {{ $root.Values.common.PGID | quote }}
        - name: UMASK
          value: "022"
      {{- if eq $k "audiobookshelf" }}
        - name: AUDIOBOOKSHELF_UID
          value: "99"
        - name: AUDIOBOOKSHELF_GID
          value: "100"
      {{- end }}
        image: {{ .repo }}/{{ $k }}:{{ .image_tag }}
        name: {{ $k }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .webui_port }}
          name: webui
      {{- if eq $k "deluge" }}
        - containerPort: {{ .torrent_port }}
          name: torrent-tcp
          protocol: TCP
        - containerPort: {{ .torrent_port }}
          name: torrent-udp
          protocol: UDP
      {{- end }}
      {{- if (or (eq $k "sonarr") (eq $k "radarr")) }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:{{ .webui_port }}/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' < /config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:{{ .webui_port }}/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' < /config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10
      {{- end }}
        volumeMounts:
        - mountPath: /config
          name: usenet-config
          subPath: {{ $k }}
        - mountPath: /arr_data
          name: usenet-media
# {{- if (or (eq $k "sonarr") (eq $k "bazarr") (eq $k "sabnzbd") (eq $k "deluge")) }}
#         - mountPath: /tv
#           name: usenet-media
#           subPath: tv
# {{- end }}
# {{- if (or (eq $k "radarr") (eq $k "bazarr") (eq $k "sabnzbd") (eq $k "deluge")) }}
#         - mountPath: /movies
#           name: usenet-media
#           subPath: movies
# {{- end }}
{{- if eq $k "readarr" }}
        - mountPath: /books
          name: usenet-media
          subPath: books
{{- end }}
{{- if eq $k "audiobookshelf" }}
        - mountPath: /metadata
          name: usenet-media
          subPath: books/metadata
{{- end }}
{{- if eq $k "audiobookshelf" }}
        - mountPath: /audiobooks
          name: usenet-media
          subPath: books
{{- end }}
{{- if eq $k "sabnzbd" }}
        - mountPath: /incomplete-downloads
          name: usenet-ssd
          subPath: incomplete
{{- end }}
# {{- if (or (eq $k "sonarr") (eq $k "radarr") (eq $k "bazarr") (eq $k "sabnzbd") (eq $k "deluge") (eq $k "readarr")) }}
#         - mountPath: /downloads
#           name: usenet-media
#           subPath: downloads
# {{- end }}
      initContainers:
      - command: ["/bin/sh", "-c"]
        args:
          - chown -R 1000:1000 /config;
            chown -R 1000:1000 /arr-data;
{{- if (or (eq $k "sonarr") (eq $k "sabnzbd") (eq $k "deluge") (eq $k "bazarr")) }}
            chown -R 1000:1000 /tv;
{{- end }}
{{- if (or (eq $k "radarr") (eq $k "sabnzbd") (eq $k "deluge") (eq $k "bazarr")) }}
            chown -R 1000:1000 /movies;
{{- end }}
            echo start;[[ ! -f /config/config.xml ]] && echo '<Config><UrlBase>/</UrlBase></Config>'> /config/config.xml;echo end;
        image: busybox
        name: chown-config
        volumeMounts:
        - mountPath: /config
          name: usenet-config
          subPath: {{ $k }}
        - mountPath: /arr_data
          name: usenet-media
# {{- if eq $k "deluge" }}
#         - mountPath: /deluge
#           name: usenet-media
#           subPath: deluge
# {{- end }}
# {{- if eq $k "sabnzbd" }}
#         - mountPath: /sabnzbd
#           name: usenet-media
#           subPath: sabnzbd
# {{- end }}
# {{- if (or (eq $k "sonarr") (eq $k "bazarr") (eq $k "radarr")) }}
#         - mountPath: /data
#           name: usenet-media
# {{- end }}
{{- if eq $k "readarr" }}
        - mountPath: /books
          name: usenet-media
          subPath: books
{{- end }}
{{- if eq $k "audiobookshelf" }}
        - mountPath: /metadata
          name: usenet-media
          subPath: books/metadata
{{- end }}
{{- if eq $k "audiobookshelf" }}
        - mountPath: /audiobooks
          name: usenet-media
          subPath: books
{{- end }}
{{- if eq $k "sabnzbd" }}
        - mountPath: /incomplete-downloads
          name: usenet-ssd
          subPath: incomplete
{{- end }}
# {{- if (or (eq $k "sonarr") (eq $k "radarr") (eq $k "bazarr") (eq $k "sabnzbd") (eq $k "deluge") (eq $k "readarr")) }}
#         - mountPath: /downloads
#           name: usenet-media
#           subPath: downloads
# {{- end }}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
      securityContext:
        fsGroup: 1000
      volumes:
      - hostPath:
          path: /storagebox/arr_data
          type: DirectoryOrCreate
        name: usenet-media
      - hostPath:
          path: /opt/usenet/config
          type: DirectoryOrCreate
        name: usenet-config
      - hostPath:
          path: /ssd-bin
          type: DirectoryOrCreate
        name: usenet-ssd

  {{- end }}
  {{- end }}
{{- end }}