{{- $root := . -}} # To load values from file outside of range loop

{{- if .Values.arr_elements }}
  {{- range $k, $v := .Values.arr_elements }}
  {{- if $v.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: usenet
  name: {{ $k }}-service
  namespace: {{ $root.Values.common.namespace }}
spec:
  ports:
  - name: webui
    port: {{ .ingress_port }}
    protocol: TCP
    targetPort: {{ .webui_port }}
  selector:
    app: usenet
    run: {{ $k }}

  {{- end }}
  {{- end }}
{{- end }}